import Image from "next/image";
import { Reveal } from "@/components/reveal";

const navItems = [["Work", "#selected-work"], ["CNP", "#cnp"], ["Systems", "#systems"], ["About", "#about"], ["Contact", "#contact"]];
const heroStats = [["10+ Years", "Audiovisual Production"], ["5+ Years", "Broadcast Production"], ["REMI", "Live & Remote Production"]];
const selectedWork = [
  { title: "Tlajtoli 2026", category: "Live Production · Event Production", description: "Direction and audiovisual production for a 90-minute institutional event.", role: "Transmission Director & Audiovisual Producer", year: "2026", href: "#tlajtoli", image: "/LFDTV%202.jpg" },
  { title: "Costa Maya", category: "Field Production · Storytelling", description: "A six-week field production across municipalities in Quintana Roo.", role: "Field Production & Editing", year: "Project archive", href: "#costa-maya" },
  { title: "CNP / TV Azteca", category: "Broadcast Operations · REMI", description: "Implementation, daily production and evolution of a remote news operation.", role: "Video Editor → Local News Producer", year: "2021–2026", href: "#cnp", image: "/IMG_20230606_190615.jpg" },
  { title: "Motion Graphics", category: "Motion · Post-production", description: "Graphic adaptation, lower thirds, transitions and motion assets.", role: "Editor", year: "Selected work", href: "#motion", media: "/cortinilla-01.mp4" },
  { title: "Selected Editing Work", category: "Digital Content · Editing", description: "Vertical content edited from client-provided footage and aligned to brand systems.", role: "Editor", year: "Selected work", href: "#editing", media: "/hubwell-01.mp4" },
];
const operationMetrics = [["7", "Daily newscasts"], ["4h+", "Daily content / production"], ["20+", "Stories reviewed per shift"], ["7–10", "Editors supervised"], ["19", "Reporters coordinated"], ["17", "CNP team members"], ["3–4", "Rundowns reviewed daily"], ["20+", "Editors trained over the operation"], ["2", "Tricaster operators trained"], ["~70%", "Approx. reduction in editing errors"]];
const timeline = [["Day 1", "Joined the third CNP implementation as Video Editor."], ["2 months", "Promoted to Local News Producer."], ["~5 months", "The team operation reached stable daily production."], ["Year 4", "Participated in operational redesign and quality-workflow evolution."], ["Year 5", "Training, documentation and knowledge-transfer processes matured."]];
const systems = ["Operational manuals", "Video tutorials", "Glossaries", "Continuity diagrams", "Visual aids", "Premiere sequence references", "Story review processes", "ISO recording processes", "Workflow documentation"];
const software = ["Adobe Premiere Pro", "After Effects", "Photoshop", "Illustrator", "Audition", "Final Cut Pro", "Tricaster", "NDI", "OBS"];

function SectionHeading({ eyebrow, title, copy }: { eyebrow: string; title: string; copy?: string }) {
  return <div className="section-heading"><p className="eyebrow">{eyebrow}</p><h2>{title}</h2>{copy && <p className="section-copy">{copy}</p>}</div>;
}

function Placeholder({ label }: { label: string }) {
  return <div className="media-placeholder" role="img" aria-label={`${label}. Media pending`}><span>MEDIA PENDING</span><strong>{label}</strong></div>;
}

export default function Home() {
  return (
    <main className="site-shell">
      <a className="skip-link" href="#main-content">Skip to content</a><div className="broadcast-grid" aria-hidden="true" />
      <header className="site-header">
        <a href="#top" className="brand" aria-label="Isaí Rodríguez, home">IRO<span>/</span>LIVE</a>
        <nav aria-label="Primary navigation">{navItems.map(([label, href]) => <a key={href} href={href}>{label}</a>)}</nav>
        <div className="header-tools"><span className="language" aria-label="Language: English. Spanish version planned"><b>EN</b><i>/</i><span>ES</span></span><span className="availability"><i />Available</span></div>
      </header>

      <section id="top" className="hero">
        <Image src="/LFDTV%202.jpg" alt="Isaí Rodríguez working in a live production environment" fill priority sizes="100vw" className="hero-image" /><div className="hero-shade" />
        <div id="main-content" className="hero-content">
          <Reveal><p className="eyebrow">Storytelling · Production · Operations · Technology</p><h1>ISAÍ<br /><span>RODRÍGUEZ</span><br /><small>ORTEGA</small></h1></Reveal>
          <Reveal delay={0.12} className="hero-positioning"><h2>Senior Video Producer <i>·</i> Broadcast Operations <i>·</i> Live Production</h2><p>I create and deliver audiovisual content across broadcast, live production and digital platforms, combining storytelling, hands-on production and scalable workflows.</p><div className="hero-actions"><a className="button primary" href="#selected-work">View selected work</a><button className="button secondary pending-action" type="button" disabled title="Showreel pending">Watch showreel <span>Coming soon</span></button><button className="text-button pending-action" type="button" disabled title="CV file pending">Download CV <span>Coming soon</span></button></div></Reveal>
          <div className="hero-stats">{heroStats.map(([value, label]) => <div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div>
        </div>
      </section>

      <section id="selected-work" className="section selected-work"><div className="section-inner">
        <SectionHeading eyebrow="01 / Portfolio" title="SELECTED WORK" copy="Selected projects across storytelling, broadcast, live production and field production." />
        <div className="work-grid">{selectedWork.map((project, index) => <Reveal key={project.title} delay={index * 0.04} className="work-card"><a href={project.href} aria-label={`View project: ${project.title}`}><div className="work-media">{project.image && <Image src={project.image} alt="" fill sizes="(min-width: 900px) 50vw, 100vw" className="cover-image" />}{project.media && <video muted playsInline preload="none" aria-hidden="true"><source src={project.media} type="video/mp4" /></video>}{!project.image && !project.media && <Placeholder label="Costa Maya field production" />}<span className="work-index">0{index + 1}</span></div><div className="work-body"><p className="card-category">{project.category}</p><h3>{project.title}</h3><p>{project.description}</p><dl><div><dt>Role</dt><dd>{project.role}</dd></div><div><dt>Year</dt><dd>{project.year}</dd></div></dl><span className="view-link">View project <b aria-hidden="true">↗</b></span></div></a></Reveal>)}</div>
      </div></section>

      <section id="tlajtoli" className="section case-study"><div className="section-inner">
        <SectionHeading eyebrow="02 / Live production" title="TLAJTOLI 2026" copy="Live production · Event production · Storytelling" />
        <div className="case-layout"><div className="case-media"><video controls playsInline preload="metadata" aria-label="Tlajtoli 2026 audiovisual production"><source src="/tlajtoali-video.mp4" type="video/mp4" />Your browser cannot play this video.</video></div><div className="case-content"><p className="client">CEDSPI · Gobierno del Estado de Hidalgo</p><h3>Director de Transmisión y Productor Audiovisual</h3><p>Dirección de transmisión del acto protocolario y producción de materiales audiovisuales para una operación multicámara de aproximadamente 90 minutos.</p><div className="fact-row"><div><strong>90 min</strong><span>Transmisión aproximada</span></div><div><strong>6</strong><span>Personas en producción</span></div><div><strong>2</strong><span>Cámaras: fija + móvil</span></div></div><ul className="detail-list"><li>Dirección de transmisión y coordinación del acto protocolario.</li><li>Producción de una cápsula institucional y un reel.</li><li>Captura y entrega de materiales audiovisuales.</li></ul><div className="tag-list">{["Sony FX30", "DJI Osmo Mobile 3", "Blackmagic", "OBS", "Adobe Premiere Pro", "Tugga MD44"].map(item => <span key={item}>{item}</span>)}</div></div></div>
      </div></section>

      <section id="costa-maya" className="section field-section"><div className="section-inner field-layout"><div><SectionHeading eyebrow="03 / Field production" title="COSTA MAYA" copy="Field production · Visual storytelling · Institutional content" /><p className="lead-copy">Proyecto especial de aproximadamente seis semanas: un recorrido audiovisual por cerca de cinco municipios para capturar lugares, actividades y tradiciones de Quintana Roo.</p><div className="fact-row"><div><strong>~6</strong><span>Semanas</span></div><div><strong>8</strong><span>Personas en el equipo</span></div><div><strong>~5</strong><span>Municipios</span></div></div><ul className="detail-list"><li>Captura de imágenes y producción en campo.</li><li>Edición de contenidos informativos y promocionales.</li><li>Producción y edición de tres notas especiales.</li><li>Selección de aproximadamente dos horas de B-roll.</li></ul></div><Placeholder label="Costa Maya photography / B-roll" /></div></section>

      <section id="cnp" className="section cnp-section"><div className="section-inner">
        <SectionHeading eyebrow="04 / Principal case study" title="BUILDING A REMOTE NEWS PRODUCTION OPERATION" copy="Third Centro Nacional de Producción · TV Azteca" />
        <div className="cnp-intro"><div className="cnp-photo"><Image src="/IMG_20230606_190615.jpg" alt="Isaí Rodríguez operating production equipment at CNP Jalisco" fill sizes="(min-width: 900px) 48vw, 100vw" className="cover-image cnp-image" /></div><div className="narrative-flow">{[["Challenge", "Joined on February 16, 2021 as a Video Editor during implementation of TV Azteca’s third Centro Nacional de Producción."], ["Implementation", "Participated from day one in process definition, continuity criteria, material delivery, training, documentation and REMI operation."], ["Operation", "Promoted approximately two months later to Local News Producer within a daily, multi-team production environment."], ["Evolution", "Worked with direction, coordination and editors to identify problems, improve quality controls and transfer operational knowledge."], ["Impact", "Contributed to a stable operation and processes associated with an approximate 70% reduction in editing errors."]].map(([stage, text]) => <div key={stage}><span>{stage}</span><p>{text}</p></div>)}</div></div>
        <div className="technical-panel"><div><p className="eyebrow">Tricaster / Technical implementation</p><h3>Configuration for the operation</h3><p>Participated in configuring Tricaster from the ground up as part of the implementation team—not as the sole designer of the CNP infrastructure.</p></div><ul>{["Virtual sets", "Wipes and transitions", "Bumpers", "Resource ingest", "Story ingest", "ISO recording preparation", "REMI workflow preparation", "Operator training"].map(item => <li key={item}>{item}</li>)}</ul></div>
        <div className="metrics-block"><div className="metrics-heading"><p className="eyebrow">Operation at scale</p><h3>A daily production environment supported and coordinated by a multidisciplinary team.</h3></div><div className="metrics-grid">{operationMetrics.map(([value, label]) => <div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div></div>
        <div className="timeline-block"><div><p className="eyebrow">Operational evolution</p><h3>From implementation to knowledge transfer.</h3><div className="tag-list process-tags">{["Process improvement", "Training", "Knowledge transfer", "Operational standardization"].map(item => <span key={item}>{item}</span>)}</div></div><ol className="timeline">{timeline.map(([time, text]) => <li key={time}><span>{time}</span><p>{text}</p></li>)}</ol></div>
      </div></section>

      <section id="systems" className="section systems-section"><div className="section-inner"><SectionHeading eyebrow="05 / Operations" title="PRODUCTION SYSTEMS & KNOWLEDGE TRANSFER" copy="Tools and documentation developed with the team to make production more consistent, teachable and scalable." /><div className="systems-grid">{systems.map((item, index) => <div key={item}><span>0{index + 1}</span><strong>{item}</strong></div>)}</div><div className="documentation-gallery"><Placeholder label="Operational manual sample" /><Placeholder label="Workflow diagram sample" /><Placeholder label="Training material sample" /></div></div></section>

      <section id="motion" className="section post-section"><div className="section-inner"><SectionHeading eyebrow="06 / Craft" title="MOTION & POST-PRODUCTION" copy="Hands-on experience across editing, montage, graphics, audio and broadcast or digital delivery." /><div className="post-layout"><div className="video-pair">{["/cortinilla-01.mp4", "/cortinilla-02.mp4"].map((src, index) => <video key={src} controls playsInline preload="none" aria-label={`Motion graphics sample ${index + 1}`}><source src={src} type="video/mp4" /></video>)}</div><div><div className="skill-copy">{["Editing and montage", "Lower thirds and motion graphics", "MOGRT templates and graphic adaptation", "Masks and compositing", "Audio editing", "Broadcast and digital deliverables"].map(item => <p key={item}>{item}</p>)}</div><div className="software-list">{software.map(item => <span key={item}>{item}</span>)}</div></div></div></div></section>

      <section id="editing" className="section editing-section"><div className="section-inner"><SectionHeading eyebrow="07 / Digital" title="SELECTED EDITING WORK" copy="Editing and brand adaptation for vertical digital content." /><div className="editing-layout"><div className="vertical-videos">{["/hubwell-01.mp4", "/hubwell-02.mp4"].map((src, index) => <video key={src} controls playsInline preload="none" aria-label={`Vertical video ${index + 1} edited for HUBWELL Logistics`}><source src={src} type="video/mp4" /></video>)}</div><div><p className="client">HUBWELL Logistics</p><h3>Editor</h3><p className="lead-copy">Edición en CapCut Pro a partir de grabaciones proporcionadas por el cliente, incorporando música, captions y tratamiento visual alineado con su paleta de color y tipografía.</p><p className="note">Plataformas de publicación no confirmadas.</p></div></div></div></section>

      <section id="collaboration" className="section collaboration-section"><div className="section-inner collaboration-layout"><SectionHeading eyebrow="08 / Collaboration" title="MULTIDISCIPLINARY COLLABORATION" /><div><p className="lead-copy">Experience coordinating production, editorial, technical and local teams within deadline-driven broadcast environments.</p><div className="collaboration-list">{["Editors", "Coordinators", "Engineering", "Operators", "Reporters", "Local producers", "On-air talent", "Local master control"].map(item => <span key={item}>{item}</span>)}</div><p className="section-copy">The work also included training, documentation and knowledge transfer between editors and operators.</p></div></div></section>

      <section id="about" className="section about-section"><div className="section-inner about-layout"><SectionHeading eyebrow="09 / About" title="PROCESS THINKING MEETS STORYTELLING" /><div><p className="lead-copy">Isaí began his professional career in industrial operations and later developed his path in audiovisual production and television. His experience connects communication, production, operations, process design and technology.</p><div className="education-grid"><article><span>2004–2009</span><h3>Licenciatura en Ciencias de la Comunicación</h3><p>Universidad Autónoma del Estado de Hidalgo</p><strong>Titulado</strong></article><article><span>2015–2019</span><h3>Ingeniería Industrial</h3><p>Instituto Tecnológico de Pachuca</p><strong>Materias concluidas · Titulación pendiente</strong></article></div></div></div></section>

      <footer id="contact" className="contact-section"><div className="section-inner contact-layout"><div><p className="eyebrow">10 / Contact</p><h2>LET&apos;S BUILD<br />THE NEXT STORY.</h2></div><div className="contact-details"><h3>Isaí Rodríguez Ortega</h3><p>Guadalajara, Jalisco, México</p><a href="mailto:orror.isai@outlook.com">orror.isai@outlook.com</a><a href="https://www.linkedin.com/in/iro/" target="_blank" rel="noreferrer">LinkedIn ↗</a><button className="button secondary pending-action" type="button" disabled title="CV file pending">Download CV <span>Coming soon</span></button></div></div><div className="footer-line"><span>IRO/LIVE</span><span>Senior Video Producer · Broadcast Operations · Live Production</span><span>© {new Date().getFullYear()}</span></div></footer>
    </main>
  );
}
